export const messages = [
  {
    position: "right",
    type: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: new Date(),
  },
  {
    position: "left",
    type: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: new Date(),
  },
  {
    position: "right",
    type: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: new Date(),
  },
  {
    position: "right",
    type: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: new Date(),
  },
  {
    position: "left",
    type: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: new Date(),
  },
  {
    position: "right",
    type: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: new Date(),
  },
  {
    position: "right",
    type: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: new Date(),
  },
  {
    position: "left",
    type: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: new Date(),
  },
  {
    position: "right",
    type: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: new Date(),
  },
  {
    position: "right",
    type: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: new Date(),
  },
  {
    position: "left",
    type: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: new Date(),
  },
  {
    position: "right",
    type: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: new Date(),
  },
  {
    position: "right",
    type: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: new Date(),
  },
  {
    position: "left",
    type: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: new Date(),
  },
  {
    position: "right",
    type: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: new Date(),
  },
  {
    position: "right",
    type: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: new Date(),
  },
  {
    position: "left",
    type: "text",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: new Date(),
  },
  {
    position: "right",
    sentByAdmin: true,
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit",
    date: 1621447881932,
  },
];

export const chatListData = [
  {
    avatar: "https://picsum.photos/200",
    alt: "Reactjs",
    title: "Facebook",
    subtitle: "What are you doing?",
    date: new Date(),
    unread: 5,
  },
  {
    avatar: "https://picsum.photos/205",
    alt: "Reactjs",
    title: "Facebook",
    subtitle: "What are you doing?",
    date: new Date(),
    unread: 0,
  },
  {
    avatar: "https://picsum.photos/210",
    alt: "Reactjs",
    title: "Facebook",
    subtitle: "What are you doing?",
    date: new Date(),
    unread: 0,
  },
];
